---
    - name: Run Mid Server on host
      docker_container:
        name: "{{ docker_name }}"
        image: andrekosak/sn-midserver:kingston
        volumes:
          - /tmp/{{ docker_name }}/logs:/opt/agent/logs
        env:
           SN_URL={{ SN_URL1 }}
           SN_USER={{ SN_USER1 }}
           SN_PASSWD={{ SN_PASSWD1 }}
           SN_MID_NAME={{ SN_MID_NAME1 }}
           
    - name: Check if container is running
      shell: uptime
      register: notes
      
    - name: update an incident
      snow_record:
        username: admin
        password: H@rkeet3465
        instance: dev17556
        state: present
        table: x_299265_cr_mid_server_table
        number: "{{ change_request_id }}"
        data:
          work_notes : "{{ notes }}"
          short_description : "Processesed by Ansible"
